apiVersion: v1
kind: Service
metadata:
  name: productpage-service
spec:
  selector:
    app: productpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9080
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-deployment
  labels:
    app: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage
        image: 232524493482.dkr.ecr.us-east-1.amazonaws.com/productpage
        ports:
        - containerPort: 9080