apiVersion: v1
kind: Service
metadata:
  name: reviews-service
spec:
  selector:
    app: reviews
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: 232524493482.dkr.ecr.us-east-1.amazonaws.com/reviews:latest
        ports:
        - containerPort: 9080